// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4xHjjLWUoSsuAgZo3YBX-9Qc5M1tOGcc',
    appId: '1:367593607036:web:e5cb0c5f2b8e4b0ac89ef9',
    messagingSenderId: '367593607036',
    projectId: 'anim-projs-cc792',
    authDomain: 'anim-projs-cc792.firebaseapp.com',
    storageBucket: 'anim-projs-cc792.appspot.com',
    measurementId: 'G-FF8M758Q7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9vGs8BBPe3jWORbykfeUijEO07dQkvjc',
    appId: '1:367593607036:android:f96142bf22ebddcec89ef9',
    messagingSenderId: '367593607036',
    projectId: 'anim-projs-cc792',
    storageBucket: 'anim-projs-cc792.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOYGSbvxr0HAHMwBpwTX6hgiGgY9i-QNU',
    appId: '1:367593607036:ios:fe4610eada94153dc89ef9',
    messagingSenderId: '367593607036',
    projectId: 'anim-projs-cc792',
    storageBucket: 'anim-projs-cc792.appspot.com',
    iosClientId: '367593607036-bjlafuj6nqsm8v2tt2g62ucsh9kki87q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixDah',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOYGSbvxr0HAHMwBpwTX6hgiGgY9i-QNU',
    appId: '1:367593607036:ios:fe4610eada94153dc89ef9',
    messagingSenderId: '367593607036',
    projectId: 'anim-projs-cc792',
    storageBucket: 'anim-projs-cc792.appspot.com',
    iosClientId: '367593607036-bjlafuj6nqsm8v2tt2g62ucsh9kki87q.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixDah',
  );
}
